In [3]:
# matrix for ingredient
import numpy as np
A=np.array([2,0,4,6,1,1,2,2,4,0,1,1,1,2,3,1,0,1,3,4,0,2,4,1,3])
ingredients=A.reshape(5,5)
print(ingredients)
np.ndim(ingredients)

[[2 0 4 6 1]
 [1 2 2 4 0]
 [1 1 1 2 3]
 [1 0 1 3 4]
 [0 2 4 1 3]]


2

In [4]:
#matrix of prices
B=np.array([200,100,200,300,100])
prices=B.reshape(5,1)
print(prices)
np.ndim(prices)

[[200]
 [100]
 [200]
 [300]
 [100]]


2

In [10]:
#multiply matrices
np.matmul(ingredients,prices)


array([[3100],
       [2000],
       [1400],
       [1700],
       [1600]])

In [11]:
#transpose of ingredients
matrix_T=(np.transpose(ingredients))
print(matrix_T)

[[2 1 1 1 0]
 [0 2 1 0 2]
 [4 2 1 1 4]
 [6 4 2 3 1]
 [1 0 3 4 3]]


In [12]:
#transpose of prices
matrix_TT=(np.transpose(prices))
print(matrix_TT)

[[200 100 200 300 100]]


In [13]:
#multiplying with a transposed matrix of ingredients
ingredients.dot(matrix_T)

array([[57, 34, 21, 28, 25],
       [34, 25, 13, 15, 16],
       [21, 13, 16, 20, 17],
       [28, 15, 20, 27, 19],
       [25, 16, 17, 19, 30]])

In [14]:
#multiplying with a transposed matrix of prices
prices.dot(matrix_TT)

array([[40000, 20000, 40000, 60000, 20000],
       [20000, 10000, 20000, 30000, 10000],
       [40000, 20000, 40000, 60000, 20000],
       [60000, 30000, 60000, 90000, 30000],
       [20000, 10000, 20000, 30000, 10000]])

In [16]:
#identity matrix
identity_m=np.eye(5,5)
print(identity_m)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [17]:
#multiplying the identity matrix with the ingredients
ingredients.dot(identity_m)

array([[2., 0., 4., 6., 1.],
       [1., 2., 2., 4., 0.],
       [1., 1., 1., 2., 3.],
       [1., 0., 1., 3., 4.],
       [0., 2., 4., 1., 3.]])

In [19]:
#multiplying the identity and transposed matrix
identity_m.dot(matrix_T)

array([[2., 1., 1., 1., 0.],
       [0., 2., 1., 0., 2.],
       [4., 2., 1., 1., 4.],
       [6., 4., 2., 3., 1.],
       [1., 0., 3., 4., 3.]])

In [21]:
#determinant of a matrix of ingredients
np.linalg.det(ingredients)

-104.99999999999997

In [22]:
#determinant of a atransposed matrix
np.linalg.det(matrix_T)

-104.99999999999997

In [ ]:
#matrix of ingredients is linearly dependant to the transpose of the matrix